### ISSUE TITLE
 Regarding the HealthRegen flag. 

### ISSUE THREAD

**Issue by RJGamers** [akdukaan/GPFlags#31]
This is a quick suggestion as i cant find any info or any option in the config.

Regarding the HealthRegen flag.

Is it possible to only allow players to do "/setflag HealthRegen 1" instead of "/setflag HealthRegen 10" or "/setflag HealthRegen 50" etc

I dont want players to set it higher than 1 as its becomes to powerfull

I hope this option can be added

Thank you

**Comment by akdukaan** [comment]
I'll have to think about the design for this but would definitely like to add it at some point

**Comment by akdukaan** [comment]
Build 51 (5.13.3-SNAPSHOT) adds the feature!
Download from https://jenkins.luminescent.dev/job/GPFlags/

By default, players who can set the flag will be capped to 1
You can change that cap to any integer by giving them the permission gpflags.flag.healthregen.5 for a max of 5

Let me know how it works!

**Comment by akdukaan** [comment]
Closing as completed
