### ISSUE TITLE
Question: How enable by default claim fly on config ?

### ISSUE THREAD

**Issue by comonier** [akdukaan/GPFlags#36]
I am using the plugin, but i not found yet, how  let it enabled by default.
It's possible? to dont need to give permissions to player enable it on own claim.

command: /setclaimflag OwnerMemberFly true | permission: `gpflags.flag.OwnerMemberFly` 
command: /setclaimflag OwnerFly true | permission: `gpflags.flag.OwnerFly`

**Comment by akdukaan** [comment]
You can use /setdefaultclaimflag to set a flag that will be enabled by default on all claims. There’s more information on its usage in the wiki.
