### ISSUE TITLE
OwnerFly and OwnerMemberFly still toggling fly on/off when flag is removed

### ISSUE THREAD

**Issue by MrPranklez** [akdukaan/GPFlags#48]
**Describe the bug**
The OwnerFly and OwnerMemberFly flags both cause the same issue; When deactivating one of these flags after having one of them active, flight gets toggled off for anyone (except for people with the bypass permission). The only way to resolve this issue is to restart the server entirely. The NoFlight flag however doesn't have this issue.

**To Reproduce**
1. Create a claim and set the OwnerFly or OwnerMemberFly flag
2. Remove the flag from the claim
3. When you enter/exit the claim fly will get toggled off for anyone (except for the people that have bypass permissions)

**Expected behavior**
If the flag is removed from the claim flight doesn't get toggled on/off

**Screenshots or Videos**

**Configs:**
 - GriefPrevention config [pastebin](https://pastebin.com/tpgWW4av)
 - GPFlags config [pastebin](https://pastebin.com/xWjE5gbw)

**Versions:**
 - GriefPrevention version: latest available version
 - GPFlags version: latest available version
 - Server version: purpur 1.19.4 latest available version

**Comment by akdukaan** [comment]
You need to give the gpflags.bypass.fly permission to the players who you want to be able to fly around the world. It was designed this way a long time ago by one of the previous developers as a way to turn off fly for people entering a region where flags like OwnerFly aren't enabled. I don't love the way it currently works, but I haven't been able to find a better method to determine which players should be able to fly in places where the flag isnt enabled. Is there a specific reason you can't give gpflags.bypass.fly to those players who should be able to fly around in the world?

**Comment by akdukaan** [comment]
Still not sure I completely understand so correct me if I'm wrong. You wanted ownerfly to enable fly on entry but not disable it when the flag is removed. In response, I suggested giving players the gpflags.bypass.fly permission. You think that my suggestion would create another problem where players would be able to fly in NoFlight areas.

If all that is correct, here's my response to that:
gpflags.bypass.fly only controls disabling fly when a player leaves an ownerfly and ownermemberfly area. It does not affect the noflight flag. Bypassing the noflight flag uses a different permission node -- gpflags.bypass.noflight. If you just give the players gpflags.bypass.fly and don't give them gpflags.bypass.noflight, things should still work as expected for your noflight flags.

**Comment by akdukaan** [comment]
No reply so I'm assumings this is resolved. Closing
