### ISSUE TITLE
New flag: Sculk growth DENY

### ISSUE THREAD

**Issue by SirvydasS** [akdukaan/GPFlags#49]
**Is your feature request related to a problem? Please describe.**
Players with withers and with sculk_catalyst griefin other players claims and in claim zone growths Sculk blocks and sculk veins.

**Describe the solution you'd like**
Make a new flag who will denied from that happing.

**Additional context**
WorldGuard have that flag and working good)
photo example:
https://prnt.sc/M23x66Jq8VwM

**Comment by akdukaan** [comment]
I should be able to make this using similar logic https://github.com/EngineHub/WorldGuard/commit/857f7468d8aa5bbb700bd18a39781b0201596ade but I also think that this might be something gp itself plans to fix

**Comment by akdukaan** [comment]
Does the noblockspread flag work to prevent scull growth? You should be able to use that for now I think

**Comment by SirvydasS** [comment]
Thank you, this works
