### ISSUE TITLE
Disabled / Red AllowBlockExplosions stops working after a restart

### ISSUE THREAD

**Issue by Analogged** [akdukaan/GPFlags#53]
**Describe the bug**
The red AllowBlockExplosions flag which should mean the flag is not set appears to be resetting on server restarting and applying the flag. This is making it so claims that dont have the flag set but is showing the red text version of AllowBlockExplosions do not allow explosions to work on the claim. However, restarting the server will still show these claims with the red AllowBlockExplosions but explosions become enabled in the claim.

**To Reproduce**
By default a claim is protected from explosions
Player turns on explosions by setting green AllowBlockExplosions and now explosions work in the claim
Player turns off / makes red AllowBlockExplosions and things cant explode in the claim
Restarting the server makes it so the red AllowBlockExplosions doesnt work and allows blocks to explode

**Expected behavior**
 Red AllowBlockExplosions should keep explosions disabled after a restart

**Versions:**
 - GriefPrevention version: de1e72d
 - GPFlags version: 5.12.8
 - Server version: PurPur 2057

**Comment by akdukaan** [comment]
Interesting bug. A flag should only turn red if it's trying to overwrite some larger area where the flag is enabled. I'm assuming that's the case here too. Is it a smaller subclaim trying to overwrite a claim? Or something else?

**Comment by akdukaan** [comment]
I tried reproducing this issue myself just now and wasn't able to. I also did some testing with parent claims and child claims and things appear to be fine with both parts of the claim being able to have different values for /claimexplosions.

Maybe I fixed it a while ago and just hadnt closed this issue? Closing this now as things appear to be working.
