### ISSUE TITLE
NoEnter Claim Flag Suggestion

### ISSUE THREAD

**Issue by At0t** [akdukaan/GPFlags#59]
If you’re flying with an elytra and run into a claim with the noenter flag enabled you just kinda get stuck and can’t move
If possible could you make it so you like fall to the ground or get turned around instead?

**Comment by akdukaan** [comment]
Can you test that out and let me know if it fixes your issue? https://jenkins.luminescent.dev/job/GPFlags/163/artifact/target/GPFlags-5.12.10-SNAPSHOT.jar

**Comment by akdukaan** [comment]
No response so I'm assuming it's fixed. Leave a comment if it's not!
