### ISSUE TITLE
Unset a claim flag for every claim from console

### ISSUE THREAD

**Issue by RJGamers** [akdukaan/GPFlags#60]
Hello DrBot. 

Please please can we get an update to allow us to remove certain claim flags from every claim that a player has.

I want to add the "Owner Fly" flag to a Rank as a perk, and when that rank expires the console will them run a command to remove the owner fly flag from all of that players claims.

For example. "/unsetclaimflagplayer <name> OwnerFly all" 
![gggggggggg](https://github.com/akdukaan/GPFlags/assets/54243352/b012986c-c2df-4b22-9d1a-8a31773a53de)

**Comment by akdukaan** [comment]
5.12.10 added this ability with /bulkunsetflag :)
