### ISSUE TITLE
Plugin halting startup.

### ISSUE THREAD

**Issue by ZepsiZola** [akdukaan/GPFlags#61]
**Describe the bug**
[This log basically shows what the issue is.](https://mclo.gs/4QHeLZa)
GPFlags starts enabling at: `[06:30:52] [Server thread/INFO]: [GPFlags] Enabling GPFlags v5.12.9`
GPFlags finishes enabling at `[06:46:44] [Server thread/INFO]: [GPFlags] Successfully loaded in 952.78 seconds`
So basically an every now and then, the plugin halts the server increases startup time by ~950 seconds due to some network stuff happening. 

**Versions:**
 - GriefPrevention version: 16.18.1
 - GPFlags version: 5.12.9
 - Server version: 1.20.1

**Additional context**

**Comment by akdukaan** [comment]
Fixed. Added a 5 second timeout and made the update checking async.
