### ISSUE TITLE
ChangeBiome flag does not change the biome in negative Y level

### ISSUE THREAD

**Issue by m-sarabi** [akdukaan/GPFlags#62]
**Describe the bug**
Using the claim flag ChangeBiome only changes the biome above Y: 0 and does not change the biome below Y: 0.

**To Reproduce**
1. Stand in a claim with biome A
2. Use the command `/claimflag ChangeBiome B` where B is another biome
3. Relog
4. Observe that biome at negative Y level stays as A

**Expected behavior**
The biome of the whole world height from top to bottom should change

**Screenshots or Videos**
![2024-04-14_07 45 19](https://github.com/akdukaan/GPFlags/assets/74133927/4d72ddfa-1e62-4444-b31b-30800acaa1e0)

**Versions:**
 - GriefPrevention : 16.18.2
 - GPFlags : 5.12.11
 - Server : 1.20.4

**Comment by akdukaan** [comment]
Fixed in the snapshot versions! https://jenkins.luminescent.dev/job/GPFlags/
