### ISSUE TITLE
Unsetting NoEnderPearl in sub-claim does not enable them

### ISSUE THREAD

**Issue by stuart2w** [akdukaan/GPFlags#65]
**Describe the bug**
The NoEnderPearl flag takes effect if the flag exists at all - the code does not check the "set" state of the flag.  

**To Reproduce**
1. /setflag NoEnderPearl in main claim
2. /unsetflag NoEnderPearl in sub-claim
3. Pearls are still blocked in the sub-claim
4. (Optional) /unsetflag NoEnderPearl in the main claim removing that flag - pearls are still blocked in the sub-claim

**Expected behavior**
Pearls should be permitted where the flag is unset

**Screenshots or Videos**
Screenshots of the /listflags result where pearls are blocked attached

![no EP 1](https://github.com/akdukaan/GPFlags/assets/58920362/a65510d0-a037-4f2f-a1e7-546d1442f9bb)
![no EP 2](https://github.com/akdukaan/GPFlags/assets/58920362/d6aad693-8845-440b-bba2-0be8f3675087)

**Additional context**
FlagDef_NoEnderPearl.java in public void onPlayerTeleport twice checks the existence of the flag, eg:
        Flag flag = this.getFlagInstanceAtLocation(event.getFrom(), event.getPlayer());
        if (flag != null) {
            Claim claim = GriefPrevention.instance.dataStore.getClaimAt(event.getFrom(), false, null);
            // etc
            }
Lines 36 and 52 should presumably read:
        if (flag != null && flag.getSet()) {

**Comment by akdukaan** [comment]
getFlagInstanceAtLocation returns null if the flag is unset so we don't need to check flag.getSet. I just tested this in my server and everything seems to work as expected. I can't reproduce the issue you're having. The flag denies teleportation both if the ender pearl is thrown from an area with the flag enabled or if the ender pearl lands in an area with the flag enabled. Could you maybe try testing again?

**Comment by stuart2w** [comment]
The flag was set at both ends of the throw.
I haven't completely got to the bottom of this, but it does look like something else is affecting this in this instance, so I'll close this.
