### ISSUE TITLE
OwnerFly: Will remain on users when they change world's with Multiverse

### ISSUE THREAD

**Issue by KoalaServers** [akdukaan/GPFlags#66]
**Describe the bug**
OwnerFly enabled, user flies within their claim, but if they /warp resource (which in our case is a seperate world manged via multiverse), will allow the user to retain and fly around.

**To Reproduce**
1. With OwnerFly enabled on a claim.
2. Create a seperate world with Multiverse.
3. Create a warp /resource to that world.
4. You can fly indefinitely.

**Expected behavior**
A user can fly indefinitely when outside of their claim.

**Comment by akdukaan** [comment]
I couldn't reproduce this on my server, but I did just try changing the delay to 2 ticks from 1. Can you check if this fixes the issue? Use build 38 or newer from [jenkins](https://jenkins.luminescent.dev/job/GPFlags/)

**Comment by KoalaServers** [comment]
Dev is very helpful! Latest build fixed this issue.
