### ISSUE TITLE
Improve the handling of players using legacy formatting codes

### ISSUE THREAD

**Issue by Voldechu** [akdukaan/GPFlags#69]
When attempting to create an enter or exit message post MiniMessage compatibility, using a legacy code (eg. "&6") will result in a successful command execution, but the message will not be seen upon entering or exiting the claim.  

This can be confusing to players who are unaware of the transition to MiniMessage formatting, and reported as a bug. (which it is, sort of) 
Can also clog up console, seeing that every time one of these dissapeared messages is triggered, the server with throw a large error. 

Instead of the message dissapearing, the exit or enter message should either 
- (Ideally) Show up as expected, with the legacy color codes visible in the message to indicate they have not worked (eg. "&6Welcome!")
- (Less ideally) Fail to format the message, but dissapear, leaving the message intact (eg. "Wecome!"
- (Worst case scenario) Fail to execute, sending an error to the user asking for the use of MiniMessage) (Not good, what if people want to use an & in their message?)
- (Impossibly Ideal) Work anyway, like older versions

**Comment by akdukaan** [comment]
I don’t see how the § could possibly be getting into the params but I’ve made it translate that character to & with build 47. Took the solution in your first bullet point
