### ISSUE TITLE
Player can fly after resawning

### ISSUE THREAD

**Issue by IAISI** [akdukaan/GPFlags#70]
**Describe the bug**

Player can fly after respawning if they were flying upon dying

**To reproduce**
Create claim
Do /setflag ownerfly
Do /suicide
You can now fly everywhere...

**Expected behavior**
Fly flag should be rechecked on respawning...

**Screenshots, videos, or logs**
If applicable, add screenshots, videos, or console logs to show the issue. You can add console logs at [binflop](https://bin.birdflop.com) and send the link here

**Configs and console errors:**
If you think it might help, paste configs into [binflop](https://bin.birdflop.com) and send the links here
 - GriefPrevention config
 - GPFlags config

**Versions:**
 - GriefPrevention version 
 - GPFlags version (ex 5.13.1)
 - Server version (ex Paper 1.20.6-144)

**Comment by IAISI** [comment]
Latest GPFlags from github as of now. Commit: https://github.com/akdukaan/GPFlags/commit/59b0edf81de2e72b0777515d18414dd9d8d25448

**Comment by IAISI** [comment]
Running 1.20.6, I should add that looking at the code it should already check on respawn and I can't reliably replicate anymore...

**Comment by akdukaan** [comment]
You could try build 48
https://jenkins.luminescent.dev/job/GPFlags/
Added a little delay for the flight check — maybe it was checking it too soon

**Comment by akdukaan** [comment]
Closing this as resolved. If you get the issue again, test on the latest snapshot and then feel free to make a new issue if that also has it
