### ISSUE TITLE
NoMonsters Trial Chamber Config Option

### ISSUE THREAD

**Issue by wyattduber** [akdukaan/GPFlags#75]
Hello,

I am writing to see if it is possible to add a config option to allow/disable the effects of the NoMonsters flag when it comes to Trial Chambers. 

We've been running into instances of players on our server being able to claim trial chambers, add the NoMonsters flag, and then claim free loot. This isn't an issue with the plugin necessarily, as it is functioning as it should. We've had to disable use of the NoMonsters flag to prevent this as we just reset our map for the 1.21 major version update and don't want players getting free loot this early into the map. 

Our players love using this flag for their personal claims, so we would like to avoid having to disable this entirely. I am not sure if this is possible from a developer perspective so please provide some insight to if this is possible.

Thanks!
Wcash

**Comment by akdukaan** [comment]
Mobs in trial chambers come from spawners, right? Have you considered using the config option to make NoMonsters not affect spawner mobs

**Comment by IAISI** [comment]
That's based on spawn reason? Trial spawners have own SpawnReason https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html#TRIAL_SPAWNER

**Comment by akdukaan** [comment]
> That's based on spawn reason? Trial spawners have own SpawnReason https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html#TRIAL_SPAWNER

Ooh thanks for this info! I guess the config option doesn’t affect trial spawners in any way at the moment. I’ll get the config option to work with trial spanwers today. When that’s done, is that going to be enough to resolve this @wyattduber ?

**Comment by wyattduber** [comment]
Yes, I think so! Thank you so much for your quick reply!!

**Comment by wyattduber** [comment]
@akdukaan Hello, sorry to bother but this change has yet to be released to my knowledge. Any idea on when this change will be released? Just curious!

**Comment by akdukaan** [comment]
> @akdukaan Hello, sorry to bother but this change has yet to be released to my knowledge. Any idea on when this change will be released? Just curious!

You can download from https://jenkins.luminescent.dev/job/GPFlags/

**Comment by wyattduber** [comment]
Thanks! I will try this.
