### ISSUE TITLE
Wither and Snow Golem Bug

### ISSUE THREAD

**Issue by Sinister-git** [akdukaan/GPFlags#81]
Bug Report:

---

**#### Describe the bug**  
There is a conflict between GriefPrevention and GPFlags plugins concerning mob protection, specifically with snow golems and withers. When the `ProtectCreatures` option in GriefPrevention's config is set to `true`, setting the `AllowWitherDamage` flag within a claim does not work as expected. If the `ProtectCreatures` option is changed to `false`, it allows withers to damage snow golems, but then flags like `NoMobDamage` fail to prevent wither damage to the snow golem. This may also affect other mobs, though this has only been tested with snow golems.

**#### To reproduce**  
1. Set up a Minecraft server running version 1.21.1 with Purpur build 2286.
2. Install GriefPrevention version 16.18.4 and GPFlags version 5.13.4.
3. Set `ProtectCreatures` to `true` in the GriefPrevention config.
4. Create a claim and set the `AllowWitherDamage` flag in that claim.
5. Summon a snow golem within the claim.
6. Summon a wither and observe that the snow golem does not take damage despite the flag.
7. Change `ProtectCreatures` to `false` in the GriefPrevention config.
8. Summon another snow golem and wither. Observe that the snow golem now takes damage, but the `NoMobDamage` flag does not prevent this damage.

**#### Expected behavior**  
When `ProtectCreatures` is set to `true`, the `AllowWitherDamage` flag should allow withers to damage snow golems within a claim. When `ProtectCreatures` is set to `false`, the `NoMobDamage` flag should prevent withers from damaging snow golems within a claim.

**#### Versions**  
Server Version: Purpur 1.21.1, build 2286  
GriefPrevention Version: 16.18.4  
GPFlags Version: 5.13.4  

---

**Comment by akdukaan** [comment]
Build 90 has fixed the issue where NoMobDamage doesn't protect snow golems when it should.
For the other half, it looks like Snowmen and withers attacking each other dont trigger EntityDamageByEntityEvent for some reason. Will look more into it later

**Comment by akdukaan** [comment]
Build 91 fixed the other half now! You can download from https://jenkins.luminescent.dev/job/GPFlags/
Let me know if it works!

**Comment by Sinister-git** [comment]
Just tested it now and seems to work as expected, thanks!
