### ISSUE TITLE
Flag ReadLecterns Crashes server

### ISSUE THREAD

**Issue by KugelblitzNinja** [akdukaan/GPFlags#84]
The use of the flag ReadLecterns crashes the server.

Steps to create issue
 - Create claim
 - Set readlecterns
 - Have other player to interact with the lectern 
      (Having the claim owner read from the lectern can also crash the server but this was not 100% of the time when testing)

the log file from this error is very large (136MB), I will attempt to upload it to this message compressed.
[Console.zip](https://github.com/user-attachments/files/17130465/Console.zip)
[crash-2024-09-25_12.37.25-server.txt](https://github.com/user-attachments/files/17130473/crash-2024-09-25_12.37.25-server.txt)

Output of /ver
  This server is running Paper version 1.21.1-99-master@1bc02e6 (2024-09-25T02:41:02Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

Output of /pl
  Server Plugins (2):
  Bukkit Plugins:
    - GPFlags, GriefPrevention

Output of /gpflags debug
  [GPFlags] Server version: Paper 1.21.1-99-1bc02e6 (MC: 1.21.1)
  [GPFlags] GP version: 16.18.4
  [GPFlags] GPF version: 5.13.5.110

**Comment by akdukaan** [comment]
I see the issue in my code causing an infinite loop. Not sure the right way to fix it just yet. Will work on it and get you a fixed build tonight.

**Comment by akdukaan** [comment]
114 should have this fixed https://jenkins.luminescent.dev/job/GPFlags/

**Comment by KugelblitzNinja** [comment]
thank you i can confirm it has been fixed.
