### ISSUE TITLE
Better Handling for NoElytra/NoEnter flags when flying around the world

### ISSUE THREAD

**Issue by ElementAnimationCouncil** [akdukaan/GPFlags#85]
**Is your feature request related to a problem? Please describe.**
Hello, a lot of my players are getting frustrated when exploring our world by flying with an elytra. If they happen to fly into a claim with NoFly on and are high off the ground, they stop flying and fall to their death; often resulting in the loss of items and they are unsure where they died. When the NoEnter flag is set on a claim they fly into, it will keep them stuck in fly mode in midair with no way of getting out except to teleport.

**Describe the solution you'd like**
I would like to see a feature for each of these flags to better handle these situations. Perhaps when they fly into a claim with NoEnter on, it will just teleport them back to the ground, or to the other side of the claim, etc. Maybe the same thing for the NoElytra flag, or it could give them slow falling and they glide to the ground. I am curious what you think would be possible.

**Describe alternatives you've considered**
I've looked around the config to see if there is a setting that would mitigate this, but there is not. I can't think of anything that I could do with other plugins, since this is an issue that is directly tied to how this plugin handles these two flags.

**Additional context**
Nothing additional to note. Please let me know if there is anything you need from me or if you have any additional questions. Thank you!

**Comment by akdukaan** [comment]
Are you using an old version of GPF? In the current version 5.13.6, neither of these should be an issue.

**Comment by ElementAnimationCouncil** [comment]
Yes, that is the version we are using and players are still reporting this issue. Is there a config setting that I am missing that would perhaps mitigate the issue? Or something else with the implementation? 
![image](https://github.com/user-attachments/assets/8a2d8755-7e82-4ae8-bca9-8e82e4fd21d1)

We are also using the most up-to-date version of GriefPrevention, if that is helpful in any way.
![image](https://github.com/user-attachments/assets/31e412ee-c623-49cf-a93b-f68bf749bf7e)

**Comment by akdukaan** [comment]
Looks like NoFlight has the code to prevent fall damage after a player's flight is disabled from the flag, but NoElytra doesn't. As for getting stuck in midair, I thought I'd fixed that earlier, but I was able to get my server to also have the same issue. Not sure if I broke it or if my fix just didn't work. Will work on both of these soon.

**Comment by akdukaan** [comment]
Issue with NoElytra fixed in 5.13.6.121 which you can download at https://jenkins.luminescent.dev/job/GPFlags/

Other issue I might need some more time to look into. Not sure why it's doing that.

**Comment by ElementAnimationCouncil** [comment]
Thank you so much! I'll drop this in and report back if I notice any bugs or regressions with this fix. I appreciate the quick responses. :)

**Comment by ArduFish** [comment]
@akdukaan what is the difference between NoElytra and NoFlight?

**Comment by ElementAnimationCouncil** [comment]
@akdukaan Just confirmed with some of our users that fall damage is indeed being negated. Thank you for your help, let me know when you find a solution for the NoEnter flag!

**Comment by akdukaan** [comment]
> @akdukaan what is the difference between NoElytra and NoFlight?
NoElytra is for gliding with elytras and NoFlight is for flying like in creative mode or with /fly



> @akdukaan Just confirmed with some of our users that fall damage is indeed being negated. Thank you for your help, let me know when you find a solution for the NoEnter flag!
Fixed in b126 https://jenkins.luminescent.dev/job/GPFlags/
