### ISSUE TITLE
Bypassing No Enter Issue

### ISSUE THREAD

**Issue by groovyloopylou** [akdukaan/GPFlags#88]
#### Describe the bug
Staff are partially being blocked from claims with the NoEnter claim flag

#### To reproduce
1. staff team has gpflags.bypass.noenter
2. staff can teleport into claim with the NoEnter flag applied and receive the message that they may not enter but can physically enter and move freely
3. Walk outside claim boundaries and try and re-enter on foot and receive the "blocked" message **and** are unable to enter claim at all this way

#### Expected behavior
no messages warning they may not enter the claim and be able to cross claim boundaries that have the flag applied

#### Screenshots, videos, or logs
n/a

#### Configs and console errors
n/a

#### Versions
Server version: Purpur 1.21.1-2329-803bf62 (MC: 1.21.1)
GP version: 16.18.4
GPF version: 5.13.6

**Comment by akdukaan** [comment]
Fixed in 5.13.6.122
