### ISSUE TITLE
Flag that doesn’t let people in there claim doesn’t work.

### ISSUE THREAD

**Issue by Timco307** [akdukaan/GPFlags#89]
When you hop on a boat and you go inside a restricted claim, it lets you but in the chat, it gives you a warning saying you can’t go in this area even though you can still go in it but when you get out of the boat or somebody breaks your boat then you get kicked out where you first started to enter the claim.

**Comment by akdukaan** [comment]
You didnt fill out the proper issue format. Update GPFlagd, test to see if the issue still exists, and if it does, then reopen this issue with the output from `/gpflags debug`

**Comment by Timco307** [comment]
Sorry I don’t use this plugin I was playing on a server and reported it to they then they said to report it my self to you guys.

**Comment by akdukaan** [comment]
> Sorry I don’t use this plugin I was playing on a server and reported it to they then they said to report it my self to you guys.

Bugs should usually be reported by server admins since they have a lot more information about their server than players. Ask the server owner to update and test, and if the issue still exists, they should be the one to fill out a bug report.
